### ISSUE TITLE
4th cell is empty in linear mode

### ISSUE THREAD

**Issue by ganaaaa** [WenchaoD/FSPagerView#44]
this issue only exists in linear mode
![item_selection_issue](https://cloud.githubusercontent.com/assets/25965156/26610898/3c5f149a-455f-11e7-81cb-0dc47952e855.gif)

**Comment by WenchaoD** [comment]
Fixed, thanks.

**Comment by ganaaaa** [comment]
i am sorry, but it's not fixed. It is not showing 4th cell when you have only 4 cells
