### ISSUE TITLE
When only 1 data don't show 3 cell

### ISSUE THREAD

**Issue by bawn** [WenchaoD/FSPagerView#46]
Great library!

I hope to when only 1 data just show 1 cell

**Comment by WenchaoD** [comment]
Fixed with [this commit](https://github.com/WenchaoD/FSPagerView/commit/23be29b3a133ffa478d3155f9afb25eb3271a812).

**Comment by bawn** [comment]
When only 1 data still show three cells in the 0.5.4 version. I try to hide other two cells but the UICollectionview is not public. Any ideas ? 

My code, There are no other special cases

```
let pagerView = FSPagerView(frame: CGRect(x: 0, y: 0, width: UIScreen.main.bounds.size.width, height: itemHeight))
        pagerView.isInfinite = true
        pagerView.automaticSlidingInterval = 5
        pagerView.delegate = self
        pagerView.dataSource = self
        pagerView.interitemSpacing = 8
        pagerView.itemSize = CGSize(width: itemWidth, height: itemHeight)
        pagerView.register(HQPagerViewCell.self, forCellWithReuseIdentifier: "cell")
        self.view.addSubview(pagerView)
```

```
public func numberOfItems(in pagerView: FSPagerView) -> Int {
        guard let array = self.bannerArray else {
            return 0
        }
        return array.count
    }
    
    public func pagerView(_ pagerView: FSPagerView, cellForItemAt index: Int) -> FSPagerViewCell {
        let cell = pagerView.dequeueReusableCell(withReuseIdentifier: "cell", at: index) as! HQPagerViewCell
        cell.config(item: self.bannerArray?[index])
        return cell
    }
```

![image](https://user-images.githubusercontent.com/7238866/27365409-941434f8-5672-11e7-8d4b-a4728de579cb.png)

**Comment by WenchaoD** [comment]
Turn of `isInfinite` if the array contains only 1 item. Please open another issue for different problem.

**Comment by bawn** [comment]
@WenchaoD Thanks
